SELECT SUM(sub.Conversion), TRANSACTION_DATE
FROM (
	SELECT TRANSACTION_DATE,
		CASE
			WHEN EXCHANGE_RATE_TO_EUR IS NULL THEN AMOUNT
			WHEN EXCHANGE_RATE_TO_EUR IS NOT NULL THEN AMOUNT*EXCHANGE_RATE_TO_EUR
			ELSE NULL
		END AS Conversion
	FROM 
		PAYMENTS p
	LEFT JOIN 
		CURRENCIES c ON p.CURRENCY = c.CURRENCY_ID
	LEFT JOIN 
		CURRENCY_RATES cr ON c.CURRENCY_ID = cr.CURRENCY_ID AND p.TRANSACTION_DATE = cr.EXCHANGE_DATE,
		BLACKLIST b
	WHERE 
		c.END_DATE is NULL AND
		p.USER_ID_SENDER NOT IN (b.USER_ID)
) sub
GROUP BY TRANSACTION_DATE
